//
//  NewsFeedListInteractor.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/3/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire
import SwiftyJSON
import enum Result.Result

final class NewsFeedListInteractor {
}

// MARK: - Extensions -

extension NewsFeedListInteractor: NewsFeedListInteractorInterface {
  func getData(completion: ([String]) -> Void) {
    let data = ["thoughtful", "trusted", "open", "smart", "adaptable", "agile", "neat", "careful"]
    completion(data)
  }
  
  static func getNewsFeedListFrom(source: String, completion: @escaping ([Article]) -> Void) {
    SessionManager.default.request(Router.newsList(source: source))
      .responseArray(keyPath: "articles") { (result: Result<[Article], NetworkError>, response: DataResponse<Any>) in
        do {
          print(result)
          let articles = try result.dematerialize()
          completion(articles)
        } catch {
          log.error(error)
        }
    }
  }
}
