//
//  NewsFeedListInterfaces.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/3/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol NewsFeedListInteractorInterface {
    static func getNewsFeedListFrom(source: String, completion: @escaping ([Article]) -> Void)
}

