//
//  NewsSourcesInterfaces.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/4/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol NewsSourcesInteractorInterface {
    static func getSourcesList(completion: @escaping ([Source]) -> Void)
}
